# Generated by Django 4.2.3 on 2023-07-26 19:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chat_id', models.CharField(max_length=56, primary_key=True, serialize=False, unique=True, verbose_name='Telegram chat id')),
                ('last_callback', models.CharField(default='none', max_length=56, verbose_name='Последний callback')),
                ('last_id', models.CharField(default='none', max_length=56, verbose_name='Последний callback ID')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Janras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janra', models.CharField(max_length=56, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Moderators',
            fields=[
                ('chat_id', models.CharField(max_length=56, primary_key=True, serialize=False, unique=True, verbose_name='Telegram chat id')),
                ('name', models.CharField(default='none', max_length=56, verbose_name='ФИО модератора')),
            ],
            options={
                'verbose_name': 'Модератор FREELANCE',
                'verbose_name_plural': 'Модераторы FREELANCE',
            },
        ),
        migrations.CreateModel(
            name='Storys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='История без названия', max_length=56, verbose_name='Название')),
                ('tg_id', models.CharField(max_length=256, verbose_name='ID в телеграмме')),
                ('time_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время и дата создания')),
                ('moderator_id', models.CharField(max_length=56, verbose_name='Автор озвучки')),
                ('janra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.janras')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
    ]
