# Generated by Django 4.2.3 on 2023-07-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderators',
            options={'verbose_name': 'Модератор', 'verbose_name_plural': 'Модераторы'},
        ),
    ]
